-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kalastaja CASCADE;
DROP TABLE IF EXISTS Pyydys CASCADE;
DROP TABLE IF EXISTS Saalistieto CASCADE;
DROP TABLE IF EXISTS Kalakaveri CASCADE;
DROP TABLE IF EXISTS Pyydystaja CASCADE;